-- サブ画面削除
EXEC DBO.ZZSP_DELETE_KAIFU_SUB @IDDOC, @PARENTDOC, @UUID

-- 回付者クリア処理
DECLARE @H_SYOZOKU NVARCHAR(20)
DECLARE @H_YAKUSYOKU NVARCHAR(20)
DECLARE @H_NAME NVARCHAR(20)
DECLARE @H_SYOZOKUCD NVARCHAR(10)
DECLARE @H_USERID NVARCHAR(10)
DECLARE @S_SYOZOKU NVARCHAR(20)
DECLARE @S_YAKUSYOKU NVARCHAR(20)
DECLARE @S_NAME NVARCHAR(20)
DECLARE @S_SYOZOKUCD NVARCHAR(10)
DECLARE @S_USERID NVARCHAR(10)

SELECT
    @H_SYOZOKU = UD.GUIItem113
    , @H_YAKUSYOKU = UD.GUIItem107
    , @H_NAME = UD.GUIItem100
    , @H_SYOZOKUCD = UD.GUIItem108
    , @H_USERID = UD.GUIItem98
FROM
    UD001070 UD
INNER JOIN
    EGGA0001 EG
ON  UD.IDDOC = EG.IDDOC
WHERE
    UD.GUIItem98 = @IDUSER
AND UD.GUIItem108 = @CDGROUP
AND EG.FGDEL = N'0'
AND EG.VLSTATUS = N'90'

IF @Approval_TYPE = N'総務関係承認書'
BEGIN
    SELECT
        @S_SYOZOKU = UD.GUIItem113
        , @S_YAKUSYOKU = UD.GUIItem107
        , @S_NAME = UD.GUIItem100
        , @S_SYOZOKUCD = UD.GUIItem108
        , @S_USERID = UD.GUIItem98
    FROM
        UD001070 UD
    INNER JOIN
        EGGA0001 EG
    ON  UD.IDDOC = EG.IDDOC
    WHERE
        UD.GUIItem98 = @IDUSER
    AND UD.GUIItem108 = @CDGROUP
    AND EG.FGDEL = N'0'
    AND EG.VLSTATUS = N'90'
END

SELECT
    ''
    , @H_SYOZOKU, @H_YAKUSYOKU, @H_NAME, @H_SYOZOKUCD, @H_USERID
    , @S_SYOZOKU, @S_YAKUSYOKU, @S_NAME, @S_SYOZOKUCD, @S_USERID
